# Configuration for BirdCLEF 2025 SED model inference

hydra:
  job:
    name: infer
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: local

# Run settings
seed: 42
device: 'cpu'
mode: 'validation'  # 'validation' or 'test'

# Data settings
fs: 32000
target_duration: 5    # Duration for inference target segments
train_duration: 10    # Duration for training segments
n_mels: 128
hop_length: 512
n_fft: 2048
f_min: 20
f_max: 16000
normal: 80  # Normalization value

# Model settings
model_name: 'seresnext26t_32x4d'
pretrained: false
in_channels: 1

# Inference settings
batch_size: 16
num_workers: 4
threshold: 0.5        # Confidence threshold for detection
infer_stride: 2.5     # Stride for sliding window inference (seconds)
selected_folds: [0, 1, 2, 3, 4]  # Folds to use for inference
folds: [0, 1, 2, 3, 4]  # Alternative specification for folds (overrides selected_folds if present)
num_folds: 5          # Total number of folds
validation_fold: 0    # Which fold to use for validation

# Model directory and paths
model_dir: './checkpoints'  # Directory containing saved model files (sed_model_fold*.pth)
output_dir: './output/infer'  # Output directory for predictions

# Additional parameters matching training config
random_shift_s: 2.0   # Random shift for RMS crop
optimizer: 'Adam'
weight_decay: 0.0
scheduler: null
criterion: 'BCEWithLogitsLoss'

# Post-processing settings
post_processing:
  apply_power_adjustment: true    # Apply power adjustment to low-ranked columns
  power_top_k: 30                 # Number of top classes to keep unchanged
  power_exponent: 2.0             # Exponent for power adjustment

  apply_time_smoothing: true      # Apply temporal smoothing
  smoothing_weights: [0.2, 0.6, 0.2]  # Weights for [previous, current, next]
