# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: local
  - spec: MelSpectrogram
  - model: EfficientNetB0

seed: 42
device: "cuda"
spectrogram_npy_path: "dummy" # 引数から指定

num_folds: 5
fold: 0
num_epochs: 25
train_batch_size: 32
valid_batch_size: 256
scheduler: "CosineAnnealingLR"
optimizer: "AdamW"
lr: 5e-4
weight_decay: 1e-5
T_max: 10
min_lr: 1e-6
criterion: "FocalLossBCE"
early_stopping: 3

# augmentation
fm_w: 24          # FrequencyMask 幅
fm_p: 0.5
tm_w: 32          # TimeMask 幅
tm_p: 0.5
gb_p: 0.5         # Gain/Bias 適用確率
rs_p: 0.3         # Resize 適用確率
cm_p: 0.7         # CutMix 適用確率
cm_alpha: 1.0

# model
drop_rate: 0.2
drop_path_rate: 0.2

# pseudo label
pl_threshold: 0.5
pl_lr_scale: 0.2    # Stage-2 learning-rate = lr * scale
pl_epochs: 4

use_holdout: true
valid_ratio: 0.05
full_train_after_pl: true
pl_success_threshold: 0.70
