# Configuration for BirdCLEF 2025 SED model training

hydra:
  job:
    name: train
    chdir: true
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dir: local

# Path to preprocessed spectrograms from 00-preprocess.py
spectrogram_npy_path: ${oc.env:SPEC_PATH,'/home/tomoya/kaggle/birdclef-2025/output/upload/tmp/preprocess/rms_crop/all_bird_data.npy'}

# Run settings
seed: 42
device: 'cuda'

# Data settings
fs: 32000
target_duration: 5    # Duration for inference target segments
train_duration: 10    # Duration for training segments
n_mels: 128
hop_length: 512
n_fft: 2048
f_min: 20
f_max: 16000
normal: 80  # Normalization value
random_shift_s: 2.0      # RMS で切り出した窓の中心を ±2 秒ランダムにずらす

# Model settings
model_name: 'seresnext26t_32x4d'
pretrained: true  # Use ImageNet pretrained weights for better initialization
in_channels: 1

# Training settings
batch_size: 32
num_workers: 4
num_epochs: 20
lr: 1e-4
min_lr: 1e-6
num_folds: 5
selected_folds: [0, 1, 2, 3, 4]  # Folds to train
optimizer: 'AdamW'
weight_decay: 0.0
T_max: 10
scheduler: "CosineAnnealingLR"
criterion: 'BCEWithLogitsLoss'
early_stopping: 3

# Augmentation settings
augmentation:
  # Audio-level augmentations (available for SED training)
  gaussian_noise: true      # Add gaussian noise
  noise_prob: 0.3          # Probability of applying noise
  noise_std: 0.01          # Standard deviation of noise

  volume_aug: true         # Volume/gain augmentation
  volume_prob: 0.3         # Probability of applying volume change
  gain_range: [0.7, 1.3]   # Range of gain multiplication

  time_stretch: true       # Time stretch augmentation (requires librosa)
  time_stretch_prob: 0.2   # Probability of applying time stretch
  stretch_range: [0.9, 1.1] # Range of time stretch rate

  # Batch-level augmentations (now implemented for SED!)
  mixup: true              # Enable mixup augmentation
  mixup_alpha: 0.4         # Mixup alpha parameter
  cutmix: true             # Enable cutmix augmentation  
  cutmix_alpha: 1.0        # CutMix alpha parameter
  
  # Spectrogram augmentations (not implemented for SED yet)
  spec_aug: false
  freq_mask_param: 10
  time_mask_param: 20
